services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chat_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.9"
